on: [push]

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: mikaelkevintannaibaho/cmps12_driver_pi:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Format code with clang-format
        run: make format 

      - name: Run cppcheck
        run: make cppcheck --quiet

      - name: Build the project (replace with your actual build command)
        run: make all
